services:
  - type: web
    name: uk-finance-jobs-api
    env: python
    buildCommand: apt-get update && apt-get install -y gcc && pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
